export { default as Customers } from './Customers'
export { default as Ecommerce } from './Ecommerce'
export { default as Employees } from './Employees'
export { default as Orders } from './Orders'
// App
export {default as Calender} from './App/Calender'
export { default as Colorpicker } from './App/Colorpicker'
export { default as Editor } from './App/Editor'
export { default as Kanban } from './App/Kanban'
// charts
export { default as Area } from './Charts/Area'
export { default as Bar } from './Charts/Bar'
export { default as ColorMaping } from './Charts/ColorMaping'
export { default as Financial } from './Charts/Financial'
export { default as Line } from './Charts/Line'
export { default as Pie } from './Charts/Pie'
export { default as Pyramid } from './Charts/Pyramid'
export { default as Stacked } from './Charts/Stacked'